# Generated by Django 5.0 on 2023-12-18 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, default='', upload_to='photos'),
        ),
    ]
