# Generated by Django 5.0 on 2023-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbookapp', '0002_entry_entry_data_entry_entry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_data',
            new_name='entry_date',
        ),
    ]
