# Generated by Django 5.0 on 2023-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbookapp', '0003_rename_entry_data_entry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
