version: "3"

services:
  guestbook:
    image: guestbook
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: guestbook-db-1
    environment:
      POSTGRES_DB: "guestbookdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: