apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: mmmlatt/guestbook-project:0.2
        imagePullPolicy: Always
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: django-secret-key
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: guestbook-secrets
              key: postgres-password
        volumeMounts:
        - name: static-volume
          mountPath: /guestbook/static
        - name: media-volume
          mountPath: /guestbook/media
        resources:
          limits:
            cpu: "0.3"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
