name: ci-build

on:
  push:
    branches: [ "implement-ci" ]
  pull_request:
    branches: [ "implement-ci" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:alpine
          ports:
            - 5432:5432
          env:
            POSTGRES_PASSWORD: testpassword
    env:
        SECRET_KEY: testsecretkey
        POSTGRES_PASSWORD: testpassword
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set environment variables
      run: |
        echo "DJANGO_TEST_DB_HOST=postgres" >> $GITHUB_ENV
    - name: Install dependencies
      working-directory: ./guestbook
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      working-directory: ./guestbook
      run: |
        pytest